#include <iostream>
#include <vector>
#include <string>
#include <string_view>
#include <random>
#include <limits>
#include <chrono>
#include <thread>
#include <cctype>

// ANSI Escape Codes
const std::string RESET   = "\033[0m";
const std::string RED     = "\033[31m";
const std::string GREEN   = "\033[32m";
const std::string YELLOW  = "\033[33m";
const std::string BLUE    = "\033[34m";
const std::string MAGENTA = "\033[35m";
const std::string CYAN    = "\033[36m";
const std::string BOLD    = "\033[1m";

// Roast Templates
const std::vector<std::string_view> ROAST_TEMPLATES = {
    "{name}'s code is so confusing even ChatGPT asked for clarification.",
    "{name} writes bugs so advanced they deserve their own documentation.",
    "If coding errors were Pokémon, {name} would've caught them all.",
    "{name}'s laptop fan works harder than their coding skills.",
    "The compiler sees {name}'s code and immediately files a complaint.",
    "{name} uses Stack Overflow so much even the website says 'welcome back.'",
    "{name}'s debugging process is basically turning it off and crying.",
    "If overthinking code was a sport, {name} would break world records.",
    "{name} writes comments like: 'Works somehow, don't touch.'",
    "{name}'s variable names look like passwords generated by aliens."
};

// Typing Animation
void typeText(const std::string& text, int delay = 20) {
    for (char ch : text) {
        std::cout << ch << std::flush;
        std::this_thread::sleep_for(std::chrono::milliseconds(delay));
    }
    std::cout << "\n";
}

// Replace {name} placeholder
std::string generateRoast(std::string_view temp, const std::string& name) {
    std::string roast(temp);

    size_t pos = roast.find("{name}");

    while (pos != std::string::npos) {
        roast.replace(pos, 6, name);
        pos = roast.find("{name}", pos + name.length());
    }

    return roast;
}

// Stylish Banner
void showBanner() {
    std::cout << RED << BOLD;
    std::cout << R"(

██████╗  ██████╗  █████╗ ███████╗████████╗
██╔══██╗██╔═══██╗██╔══██╗██╔════╝╚══██╔══╝
██████╔╝██║   ██║███████║███████╗   ██║
██╔══██╗██║   ██║██╔══██║╚════██║   ██║
██║  ██║╚██████╔╝██║  ██║███████║   ██║
╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝   ╚═╝

)";
    std::cout << RESET;

    std::cout << YELLOW << BOLD
              << "============================================\n"
              << "      🔥 ULTIMATE PROGRAMMER ROASTER 🔥\n"
              << "============================================\n\n"
              << RESET;
}

int main() {

    // Modern Random Generator
    std::random_device rd;
    std::mt19937 gen(rd());

    std::uniform_int_distribution<size_t> dist(0, ROAST_TEMPLATES.size() - 1);

    showBanner();

    std::string name;

    std::cout << CYAN << "Enter programmer name: " << RESET;
    std::getline(std::cin, name);

    if (name.empty()) {
        name = "Mystery Coder";
    }

    char choice = 'y';

    while (std::tolower(choice) == 'y') {

        // Random roast selection
        size_t randomIndex = dist(gen);

        std::string roast =
            generateRoast(ROAST_TEMPLATES[randomIndex], name);

        std::cout << GREEN << "\nGenerating roast";
        for (int i = 0; i < 3; i++) {
            std::cout << "." << std::flush;
            std::this_thread::sleep_for(std::chrono::milliseconds(400));
        }

        std::cout << "\n\n";

        // Display roast with typing effect
        std::cout << MAGENTA << BOLD << "[ SYSTEM ATTACK ] ➜ "
                  << RESET;

        typeText(roast, 25);

        std::cout << "\n";

        // Menu
        std::cout << BLUE
                  << "--------------------------------------------\n"
                  << RESET;

        std::cout << CYAN
                  << "Want another roast? (y/n): "
                  << RESET;

        std::cin >> choice;

        std::cin.ignore(
            std::numeric_limits<std::streamsize>::max(),
            '\n'
        );
    }

    std::cout << RED << BOLD
              << "\nSystem shutting down...\n"
              << RESET;

    typeText("Remember: Bugs fear good programmers. 😎", 30);

    return 0;
}
